# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
testdata_dir = "./.air/testdata"
tmp_dir = "./.air"

[build]
  args_bin = []
  # Binary file yields from `cmd`.
  bin = "./.air/main"
  # Just plain old shell command. You could use `make` as well.
  cmd = "go build -o ./.air/main ./.air/docker.go"
  # It's not necessary to trigger build each time file changes if it's too frequent.
  delay = 1000
  # Ignore these filename extensions or directories.
  exclude_dir = ["assets", "bin", "tmp", "vendor", "testdata", "example"]
  # Exclude files.
  exclude_file = []
  # Exclude specific regular expressions.
  exclude_regex = ["_test.go"]
  # Exclude unchanged files.
  exclude_unchanged = false
  # Follow symlink for directories
  follow_symlink = false
  # Customize binary, can setup environment variables when run your app.
  full_bin = ""
  # Watch these directories if you specified.
  include_dir = []
  # Watch these filename extensions.
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Delay after sending Interrupt signal
  kill_delay = "0s"
  # This log file places in your tmp_dir.
  log = "build-errors.log"
  # Send Interrupt signal before killing process (windows does not support this feature)
  send_interrupt = false
  # Stop running old binary when build errors occur.
  stop_on_error = true

[color]
  # Customize each part's color. If no color found, use the raw app log.
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  # Show log time
  time = true

[misc]
  # Delete tmp directory on exit
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
